### ISSUE TITLE
Workthough add new sprites

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/service-tileservergl#10]
Try and describe how to add new sprites.
Formalize.
Investigate.

**Comment by swissmap** [comment]
Description is placed here (on 20180411):
[https://github.com/geoadmin/service-tileservergl/wiki/Generating-Sprites](url)

**Comment by swissmap** [comment]
Description see:
https://github.com/geoadmin/service-tileservergl/wiki/Generating-Sprites
