### ISSUE TITLE
Save style from maputnik to github

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/service-tileservergl#12]
Investigate solutions

**Comment by loicgasser** [comment]
That s how openmaptiles handle style packaging.
https://github.com/klokantech/gl-style-package-spec
Each style has an individual repository and is tested/modified using the piece of logic in this repo.
Could be a good solution for us as well.

**Comment by loicgasser** [comment]
1. Load config file from URL
2. Enable style loading from URL
3. Save style with [PUT](https://github.com/maputnik/editor/blob/e9daee447039676c23cb94a36f5d78ca249e82ee/src/libs/apistore.js#L58)
4. Auto create config file

**Comment by loicgasser** [comment]
https://developer.github.com/v3/repos/contents/#update-a-file

Using gitub api.

**Comment by oterral** [comment]
https://github.com/maputnik/editor/issues/155

**Comment by danduk82** [comment]
put it here : https://github.com/geoadmin/config-tileserver-gl

**Comment by oterral** [comment]
Done in service-maputnik

**Comment by danduk82** [comment]
+1 Champagne!
